version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "konradmalik"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "konradmalik"

  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "06:00"
      timezone: "Europe/Warsaw"
    groups:
      flake:
        patterns:
          - "*"
    assignees:
      - "konradmalik"
